server:
  port: 8761

Spring:
  application:
    name: EurekaServerDemo

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
